%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/xuy/yun_download/testing/rgbd_dataset_freiburg1_xyz

# camera intrinsics
# fr1
camera.fx: 517.306408
camera.fy: 516.469215
camera.cx: 318.643040
camera.cy: 255.313989

camera.depth_scale: 5000

# VO paras
num_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_transfer: 0.1
